apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sumit-test-cert
  namespace: hwsql
spec:
  secretName: sumit-test-cert-secret
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - sumit.cfs.in.net
