apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: sam3ctc@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-key
    solvers:
      - dns01:
          azureDNS:
            clientID: edc3f9ff-6364-4379-8bf3-274887823ae7
            clientSecretSecretRef:
              name: azure-dns-secret
              key: clientSecret
            subscriptionID: c7c0c81d-79ac-49eb-8aa0-c9f16e51cca1
            tenantID: 7c3fa37e-f2a8-47cc-8aa7-0e7512a6e0bc
            resourceGroupName: hello-world-rg
            hostedZoneName: cfs.in.net
