apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sumit-test-ingress
  namespace: hwsql
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - sumit.cfs.in.net
      secretName: sumit-test-cert-secret  # Correct indentation

  rules:
    - host: sumit.cfs.in.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: hello-world
                port:
                  number: 8080
